name: Build and deploy Node.js app to Azure Web App - greenstackwebapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
       
      - name: Skip preflight check
        run: echo "SKIP_PREFLIGHT_CHECK=true" > .env
       
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          npm test -- --watchAll=false --ci --reporters=default --reporters=jest-junit
          
      - name: Build project
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build/

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'greenstackwebapp'
          slot-name: 'Production'
          package: build/
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_GREENUP}}